server:
  port: 8000
logging:
  level:
    root: INFO
spring:
  application:
    name: microservice-provider-userr
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    schema:
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true